//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVZ_2_1.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PVZ_2_1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BoomDie {
            get {
                object obj = ResourceManager.GetObject("BoomDie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BucketheadZombie {
            get {
                object obj = ResourceManager.GetObject("BucketheadZombie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BucketheadZombieAttack {
            get {
                object obj = ResourceManager.GetObject("BucketheadZombieAttack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Button {
            get {
                object obj = ResourceManager.GetObject("Button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConeheadZombie {
            get {
                object obj = ResourceManager.GetObject("ConeheadZombie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConeheadZombieAttack {
            get {
                object obj = ResourceManager.GetObject("ConeheadZombieAttack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FlagMeterParts1 {
            get {
                object obj = ResourceManager.GetObject("FlagMeterParts1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FlagZombie {
            get {
                object obj = ResourceManager.GetObject("FlagZombie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FlagZombieAttack {
            get {
                object obj = ResourceManager.GetObject("FlagZombieAttack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FlagZombieLostHead {
            get {
                object obj = ResourceManager.GetObject("FlagZombieLostHead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FlagZombieLostHeadAttack {
            get {
                object obj = ResourceManager.GetObject("FlagZombieLostHeadAttack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap options_menuback {
            get {
                object obj = ResourceManager.GetObject("options_menuback", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoleVaultingZombie {
            get {
                object obj = ResourceManager.GetObject("PoleVaultingZombie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoleVaultingZombieAttack {
            get {
                object obj = ResourceManager.GetObject("PoleVaultingZombieAttack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoleVaultingZombieDie {
            get {
                object obj = ResourceManager.GetObject("PoleVaultingZombieDie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoleVaultingZombieHead {
            get {
                object obj = ResourceManager.GetObject("PoleVaultingZombieHead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoleVaultingZombieJump {
            get {
                object obj = ResourceManager.GetObject("PoleVaultingZombieJump", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoleVaultingZombieJump2 {
            get {
                object obj = ResourceManager.GetObject("PoleVaultingZombieJump2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoleVaultingZombieLostHead {
            get {
                object obj = ResourceManager.GetObject("PoleVaultingZombieLostHead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoleVaultingZombieLostHeadAttack {
            get {
                object obj = ResourceManager.GetObject("PoleVaultingZombieLostHeadAttack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoleVaultingZombieLostHeadWalk {
            get {
                object obj = ResourceManager.GetObject("PoleVaultingZombieLostHeadWalk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PoleVaultingZombieWalk {
            get {
                object obj = ResourceManager.GetObject("PoleVaultingZombieWalk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sun {
            get {
                object obj = ResourceManager.GetObject("Sun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap win {
            get {
                object obj = ResourceManager.GetObject("win", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zombie {
            get {
                object obj = ResourceManager.GetObject("Zombie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zombie2 {
            get {
                object obj = ResourceManager.GetObject("Zombie2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Zombie3 {
            get {
                object obj = ResourceManager.GetObject("Zombie3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZombieAttack {
            get {
                object obj = ResourceManager.GetObject("ZombieAttack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZombieDie {
            get {
                object obj = ResourceManager.GetObject("ZombieDie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZombieHead {
            get {
                object obj = ResourceManager.GetObject("ZombieHead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZombieLostHead {
            get {
                object obj = ResourceManager.GetObject("ZombieLostHead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZombieLostHeadAttack {
            get {
                object obj = ResourceManager.GetObject("ZombieLostHeadAttack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZombiesWon {
            get {
                object obj = ResourceManager.GetObject("ZombiesWon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 僵尸正在接近 {
            get {
                object obj = ResourceManager.GetObject("僵尸正在接近", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 冒险模式1 {
            get {
                object obj = ResourceManager.GetObject("冒险模式1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 冒险模式2 {
            get {
                object obj = ResourceManager.GetObject("冒险模式2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 准备 {
            get {
                object obj = ResourceManager.GetObject("准备", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 卡片槽 {
            get {
                object obj = ResourceManager.GetObject("卡片槽", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 卡片背景 {
            get {
                object obj = ResourceManager.GetObject("卡片背景", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 卡片选择栏 {
            get {
                object obj = ResourceManager.GetObject("卡片选择栏", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 双发射手 {
            get {
                object obj = ResourceManager.GetObject("双发射手", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 向日葵 {
            get {
                object obj = ResourceManager.GetObject("向日葵", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 喷菇子弹 {
            get {
                object obj = ResourceManager.GetObject("喷菇子弹", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 喷菇子弹碰撞 {
            get {
                object obj = ResourceManager.GetObject("喷菇子弹碰撞", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 坚果墙1 {
            get {
                object obj = ResourceManager.GetObject("坚果墙1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 坚果墙2 {
            get {
                object obj = ResourceManager.GetObject("坚果墙2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 坚果墙3 {
            get {
                object obj = ResourceManager.GetObject("坚果墙3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 大喷菇 {
            get {
                object obj = ResourceManager.GetObject("大喷菇", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 大喷菇子弹 {
            get {
                object obj = ResourceManager.GetObject("大喷菇子弹", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 大喷菇攻击 {
            get {
                object obj = ResourceManager.GetObject("大喷菇攻击", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 大阳光菇 {
            get {
                object obj = ResourceManager.GetObject("大阳光菇", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 寒冰子弹1 {
            get {
                object obj = ResourceManager.GetObject("寒冰子弹1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 寒冰子弹2 {
            get {
                object obj = ResourceManager.GetObject("寒冰子弹2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 寒冰射手 {
            get {
                object obj = ResourceManager.GetObject("寒冰射手", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 小喷菇 {
            get {
                object obj = ResourceManager.GetObject("小喷菇", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 小阳光菇 {
            get {
                object obj = ResourceManager.GetObject("小阳光菇", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 帮助1 {
            get {
                object obj = ResourceManager.GetObject("帮助1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 帮助2 {
            get {
                object obj = ResourceManager.GetObject("帮助2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 摇滚背景1 {
            get {
                object obj = ResourceManager.GetObject("摇滚背景1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 摇滚背景2 {
            get {
                object obj = ResourceManager.GetObject("摇滚背景2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 最后一波 {
            get {
                object obj = ResourceManager.GetObject("最后一波", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 木头 {
            get {
                object obj = ResourceManager.GetObject("木头", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 机枪射手 {
            get {
                object obj = ResourceManager.GetObject("机枪射手", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 模式选择背景 {
            get {
                object obj = ResourceManager.GetObject("模式选择背景", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 樱桃炸弹 {
            get {
                object obj = ResourceManager.GetObject("樱桃炸弹", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 欢迎回来 {
            get {
                object obj = ResourceManager.GetObject("欢迎回来", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 火 {
            get {
                object obj = ResourceManager.GetObject("火", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 火子弹1 {
            get {
                object obj = ResourceManager.GetObject("火子弹1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 火子弹2 {
            get {
                object obj = ResourceManager.GetObject("火子弹2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 火炬树桩 {
            get {
                object obj = ResourceManager.GetObject("火炬树桩", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 火爆辣椒 {
            get {
                object obj = ResourceManager.GetObject("火爆辣椒", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 火爆辣椒攻击 {
            get {
                object obj = ResourceManager.GetObject("火爆辣椒攻击", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 炸 {
            get {
                object obj = ResourceManager.GetObject("炸", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 点击我1 {
            get {
                object obj = ResourceManager.GetObject("点击我1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 点击我2 {
            get {
                object obj = ResourceManager.GetObject("点击我2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 点击进入 {
            get {
                object obj = ResourceManager.GetObject("点击进入", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 玩玩小游戏1 {
            get {
                object obj = ResourceManager.GetObject("玩玩小游戏1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 玩玩小游戏2 {
            get {
                object obj = ResourceManager.GetObject("玩玩小游戏2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 生存模式1 {
            get {
                object obj = ResourceManager.GetObject("生存模式1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 生存模式2 {
            get {
                object obj = ResourceManager.GetObject("生存模式2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 白天背景 {
            get {
                object obj = ResourceManager.GetObject("白天背景", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 确定退出 {
            get {
                object obj = ResourceManager.GetObject("确定退出", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 菜单墓碑 {
            get {
                object obj = ResourceManager.GetObject("菜单墓碑", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 解谜模式1 {
            get {
                object obj = ResourceManager.GetObject("解谜模式1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 解谜模式2 {
            get {
                object obj = ResourceManager.GetObject("解谜模式2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 豌豆子弹1 {
            get {
                object obj = ResourceManager.GetObject("豌豆子弹1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 豌豆子弹2 {
            get {
                object obj = ResourceManager.GetObject("豌豆子弹2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 豌豆子弹碰撞 {
            get {
                object obj = ResourceManager.GetObject("豌豆子弹碰撞", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 豌豆射手 {
            get {
                object obj = ResourceManager.GetObject("豌豆射手", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 退出1 {
            get {
                object obj = ResourceManager.GetObject("退出1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 退出2 {
            get {
                object obj = ResourceManager.GetObject("退出2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 选项1 {
            get {
                object obj = ResourceManager.GetObject("选项1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 选项2 {
            get {
                object obj = ResourceManager.GetObject("选项2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 铲子1 {
            get {
                object obj = ResourceManager.GetObject("铲子1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 铲子2 {
            get {
                object obj = ResourceManager.GetObject("铲子2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 铲子3 {
            get {
                object obj = ResourceManager.GetObject("铲子3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 阳光数背景 {
            get {
                object obj = ResourceManager.GetObject("阳光数背景", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 黑夜背景 {
            get {
                object obj = ResourceManager.GetObject("黑夜背景", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
